### ISSUE TITLE
Input non conforme alle specifiche

### ISSUE THREAD

**Issue by dario-campagna** [software-development-methods-19-20/string-calculator-xcesco#1]
https://github.com/software-development-methods-19-20/string-calculator-xcesco/blob/fbec7a284bb5eef1c874974f9de2787458299492/test/source/test/AddNumbersTest.java#L44

Perché ```\\n```? La string in input dovrebbe essere ```"//;\n1;2"```. Lo stesso vale per gli altri test su delimitatori custom.

**Comment by xcesco** [comment]
Preso dal brio delle //, ho raddoppiato anche il backslash dell'invio. Risolto con https://github.com/software-development-methods-19-20/string-calculator-xcesco/issues/7 (ho creato lun'altra segnalazione perche' non mi ero accorto di questa).
