### ISSUE TITLE
Espressività

### ISSUE THREAD

**Issue by dario-campagna** [software-development-methods-19-20/string-calculator-xcesco#3]
https://github.com/software-development-methods-19-20/string-calculator-xcesco/blob/fbec7a284bb5eef1c874974f9de2787458299492/production/source/dss/calculator/StringCalculator.java#L21

Questa riga di codice fa molte cose utilizzando un ```if``` e operazioni su ```Stream```. Potrebbe essere ressa più espressiva?

**Comment by xcesco** [comment]
Ho portato la gestione dello stream in un metodo con nome un po' piu' parlante (spero).

Vedi commit associato alla issue #6
