### ISSUE TITLE
Espressività

### ISSUE THREAD

**Issue by dario-campagna** [software-development-methods-19-20/string-calculator-xcesco#4]
https://github.com/software-development-methods-19-20/string-calculator-xcesco/blob/fbec7a284bb5eef1c874974f9de2787458299492/production/source/dss/calculator/StringCalculator.java#L34

Il nome di questo metodo è molto generico, da esso non è chiaro cosa fa. Solo esaminando il codice del metodo si comprende che stringa otterremo in uscita.

Il metodo manipola stringhe e potrebbe essere reso più espressivo dando dei nomi alle operazioni che vengono effettuate con ```substring``` e altri metodi.

**Comment by xcesco** [comment]
Rinominato metodo in extractNumbersAndReplaceSeparators
